/* ---------------------- Static universe & state ---------------------- */
export const COINS = [
  {id:"bitcoin",symbol:"BTC",name:"Bitcoin"},{id:"ethereum",symbol:"ETH",name:"Ethereum"},{id:"crypto-com-chain",symbol:"CRO",name:"Cronos"},{id:"tether",symbol:"USDT",name:"Tether"},
  {id:"binancecoin",symbol:"BNB",name:"BNB"},{id:"solana",symbol:"SOL",name:"Solana"},{id:"usd-coin",symbol:"USDC",name:"USDC"},
  {id:"ripple",symbol:"XRP",name:"XRP"},{id:"toncoin",symbol:"TON",name:"Toncoin"},{id:"dogecoin",symbol:"DOGE",name:"Dogecoin"},
  {id:"cardano",symbol:"ADA",name:"Cardano"},{id:"shiba-inu",symbol:"SHIB",name:"Shiba Inu"},{id:"avalanche-2",symbol:"AVAX",name:"Avalanche"},
  {id:"tron",symbol:"TRX",name:"TRON"},{id:"polkadot",symbol:"DOT",name:"Polkadot"},{id:"bitcoin-cash",symbol:"BCH",name:"Bitcoin Cash"},
  {id:"chainlink",symbol:"LINK",name:"Chainlink"},{id:"near",symbol:"NEAR",name:"NEAR Protocol"},{id:"matic-network",symbol:"MATIC",name:"Polygon"},
  {id:"litecoin",symbol:"LTC",name:"Litecoin"},{id:"dai",symbol:"DAI",name:"Dai"},{id:"leo-token",symbol:"LEO",name:"LEO Token"},
  {id:"uniswap",symbol:"UNI",name:"Uniswap"},{id:"internet-computer",symbol:"ICP",name:"Internet Computer"},{id:"ethereum-classic",symbol:"ETC",name:"Ethereum Classic"},
  {id:"aptos",symbol:"APT",name:"Aptos"},{id:"render-token",symbol:"RNDR",name:"Render"},{id:"hedera-hashgraph",symbol:"HBAR",name:"Hedera"},
  {id:"stellar",symbol:"XLM",name:"Stellar"},{id:"cosmos",symbol:"ATOM",name:"Cosmos"},{id:"monero",symbol:"XMR",name:"Monero"},
  {id:"arbitrum",symbol:"ARB",name:"Arbitrum"},{id:"kaspa",symbol:"KAS",name:"Kaspa"},{id:"filecoin",symbol:"FIL",name:"Filecoin"},
  {id:"maker",symbol:"MKR",name:"Maker"},{id:"stx",symbol:"STX",name:"Stacks"},{id:"vechain",symbol:"VET",name:"VeChain"},
  {id:"optimism",symbol:"OP",name:"Optimism"},{id:"the-graph",symbol:"GRT",name:"The Graph"},{id:"injective-protocol",symbol:"INJ",name:"Injective"},
  {id:"aave",symbol:"AAVE",name:"Aave"},{id:"theta-token",symbol:"THETA",name:"Theta Network"},{id:"fantom",symbol:"FTM",name:"Fantom"},
  {id:"lidodao",symbol:"LDO",name:"Lido DAO"},{id:"thorchain",symbol:"RUNE",name:"THORChain"},{id:"arweave",symbol:"AR",name:"Arweave"},
  {id:"fetch-ai",symbol:"FET",name:"Fetch.ai"},{id:"algorand",symbol:"ALGO",name:"Algorand"},{id:"quant-network",symbol:"QNT",name:"Quant"},
  {id:"gala",symbol:"GALA",name:"Gala"},{id:"flow",symbol:"FLOW",name:"Flow"},{id:"eos",symbol:"EOS",name:"EOS"},
  {id:"multiversx",symbol:"EGLD",name:"MultiversX"},{id:"axie-infinity",symbol:"AXS",name:"Axie Infinity"},{id:"sandbox",symbol:"SAND",name:"The Sandbox"},
  {id:"neo",symbol:"NEO",name:"NEO"},{id:"tezos",symbol:"XTZ",name:"Tezos"},{id:"chiliz",symbol:"CHZ",name:"Chiliz"},
  {id:"kava",symbol:"KAVA",name:"Kava"},{id:"mina-protocol",symbol:"MINA",name:"Mina"},{id:"klay-token",symbol:"KLAY",name:"Klaytn"},
  {id:"iota",symbol:"IOTA",name:"IOTA"},{id:"decentraland",symbol:"MANA",name:"Decentraland"},{id:"kucoin-shares",symbol:"KCS",name:"KuCoin Token"},
  {id:"curve-dao-token",symbol:"CRV",name:"Curve DAO"},{id:"frax-share",symbol:"FXS",name:"Frax Share"},{id:"ecash",symbol:"XEC",name:"eCash"},
  {id:"bittorrent",symbol:"BTT",name:"BitTorrent"},{id:"zcash",symbol:"ZEC",name:"Zcash"},{id:"trust-wallet-token",symbol:"TWT",name:"Trust Wallet"},
  {id:"havven",symbol:"SNX",name:"Synthetix"},{id:"conflux-token",symbol:"CFX",name:"Conflux"},{id:"pepe",symbol:"PEPE",name:"Pepe"},
  {id:"floki",symbol:"FLOKI",name:"Floki"},{id:"gmx",symbol:"GMX",name:"GMX"},{id:"rocket-pool",symbol:"RPL",name:"Rocket Pool"},
  {id:"terra-luna-2",symbol:"LUNA",name:"Terra"},{id:"gatechain-token",symbol:"GT",name:"GateToken"},{id:"oasis-network",symbol:"ROSE",name:"Oasis Network"},
  {id:"blur",symbol:"BLUR",name:"Blur"},{id:"sui",symbol:"SUI",name:"Sui"},{id:"pax-gold",symbol:"PAXG",name:"PAX Gold"},
  {id:"compound-governance-token",symbol:"COMP",name:"Compound"},{id:"zilliqa",symbol:"ZIL",name:"Zilliqa"},{id:"dash",symbol:"DASH",name:"Dash"},
  {id:"1inch",symbol:"1INCH",name:"1inch"},{id:"loopring",symbol:"LRC",name:"Loopring"},{id:"pancakeswap-token",symbol:"CAKE",name:"PancakeSwap"},
  {id:"basic-attention-token",symbol:"BAT",name:"Basic Attention Token"},{id:"enjincoin",symbol:"ENJ",name:"Enjin Coin"},{id:"qtum",symbol:"QTUM",name:"Qtum"},
  {id:"mask-network",symbol:"MASK",name:"Mask Network"},{id:"celo",symbol:"CELO",name:"Celo"},{id:"nem",symbol:"XEM",name:"NEM"},
  {id:"osmosis",symbol:"OSMO",name:"Osmosis"},{id:"convex-finance",symbol:"CVX",name:"Convex Finance"},{id:"yearn-finance",symbol:"YFI",name:"yearn.finance"},
  {id:"ankr",symbol:"ANKR",name:"Ankr"},{id:"ravencoin",symbol:"RVN",name:"Ravencoin"},{id:"0x",symbol:"ZRX",name:"0x Protocol"},
  {id:"stepn",symbol:"GMT",name:"STEPN"},{id:"wax",symbol:"WAXP",name:"WAX"},{id:"audius",symbol:"AUDIO",name:"Audius"},
  {id:"siacoin",symbol:"SC",name:"Siacoin"},{id:"holo",symbol:"HOT",name:"Holo"},{id:"band-protocol",symbol:"BAND",name:"Band Protocol"},
  {id:"ontology",symbol:"ONT",name:"Ontology"},{id:"iostoken",symbol:"IOST",name:"IOST"},{id:"digibyte",symbol:"DGB",name:"DigiByte"},
  {id:"kadena",symbol:"KDA",name:"Kadena"},{id:"moonbeam",symbol:"GLMR",name:"Moonbeam"},{id:"skale",symbol:"SKL",name:"SKALE"},
  {id:"livepeer",symbol:"LPT",name:"Livepeer"},{id:"icon",symbol:"ICX",name:"ICON"},{id:"secret",symbol:"SCRT",name:"Secret"},
  {id:"just",symbol:"JST",name:"JUST"},{id:"cartesi",symbol:"CTSI",name:"Cartesi"},{id:"api3",symbol:"API3",name:"API3"},
  {id:"biconomy",symbol:"BICO",name:"Biconomy"},{id:"galxe",symbol:"GAL",name:"Galxe"},{id:"moonriver",symbol:"MOVR",name:"Moonriver"},
  {id:"origin-protocol",symbol:"OGN",name:"Origin Protocol"},{id:"chromia",symbol:"CHR",name:"Chromia"},{id:"superfarm",symbol:"SUPER",name:"SuperVerse"},
  {id:"coti",symbol:"COTI",name:"COTI"},{id:"syscoin",symbol:"SYS",name:"Syscoin"},{id:"hive",symbol:"HIVE",name:"Hive"},
  {id:"status",symbol:"SNT",name:"Status"},{id:"dent",symbol:"DENT",name:"Dent"},{id:"ocean-protocol",symbol:"OCEAN",name:"Ocean Protocol"},
  {id:"power-ledger",symbol:"POWR",name:"Powerledger"},{id:"civic",symbol:"CVC",name:"Civic"},{id:"stormx",symbol:"STMX",name:"StormX"},
  {id:"numeraire",symbol:"NMR",name:"Numeraire"},{id:"request-network",symbol:"REQ",name:"Request"},{id:"metal",symbol:"MTL",name:"Metal DAO"},
  {id:"nkn",symbol:"NKN",name:"NKN"},{id:"funfair",symbol:"FUN",name:"FUNToken"},{id:"rlc",symbol:"RLC",name:"iExec RLC"},
  {id:"ark",symbol:"ARK",name:"Ark"},{id:"verge",symbol:"XVG",name:"Verge"},{id:"steem",symbol:"STEEM",name:"Steem"},
  {id:"bancor",symbol:"BNT",name:"Bancor"},{id:"augur",symbol:"REP",name:"Augur"},{id:"nano",symbol:"XNO",name:"Nano"},
  {id:"kyber-network-crystal",symbol:"KNC",name:"Kyber Network"},{id:"uma",symbol:"UMA",name:"UMA"},{id:"sushi",symbol:"SUSHI",name:"SushiSwap"},
  {id:"balancer",symbol:"BAL",name:"Balancer"},{id:"badger-dao",symbol:"BADGER",name:"Badger DAO"},{id:"perpetual-protocol",symbol:"PERP",name:"Perpetual Protocol"},
  {id:"reef",symbol:"REEF",name:"Reef"},{id:"dodo",symbol:"DODO",name:"DODO"},{id:"alpha-finance",symbol:"ALPHA",name:"Stella"},
  {id:"prom",symbol:"PROM",name:"Prom"},{id:"linear",symbol:"LINA",name:"Linear"},{id:"idex",symbol:"IDEX",name:"IDEX"},
  {id:"polymath",symbol:"POLY",name:"Polymath"},{id:"bakerytoken",symbol:"BAKE",name:"BakeryToken"},{id:"burger-swap",symbol:"BURGER",name:"BurgerCities"},
  {id:"cream-2",symbol:"CREAM",name:"Cream Finance"},{id:"farm",symbol:"FARM",name:"Harvest Finance"},{id:"keep-network",symbol:"KEEP",name:"Keep Network"},
  {id:"nu-cypher",symbol:"NU",name:"NuCypher"},{id:"threshold-network-token",symbol:"T",name:"Threshold"},{id:"ren",symbol:"REN",name:"Ren"},
  {id:"raydium",symbol:"RAY",name:"Raydium"},{id:"serum",symbol:"SRM",name:"Serum"},{id:"star-atlas-dao",symbol:"POLIS",name:"Star Atlas DAO"},
  {id:"orca",symbol:"ORCA",name:"Orca"},{id:"marinade-staked-sol",symbol:"MSOL",name:"Marinade Staked SOL"},{id:"lido-staked-sol",symbol:"STSOL",name:"Lido Staked SOL"},
  {id:"marlin",symbol:"POND",name:"Marlin"},{id:"lcx",symbol:"LCX",name:"LCX"},{id:"dia-data",symbol:"DIA",name:"DIA"},
  {id:"covalent",symbol:"CQT",name:"Covalent"},{id:"tellor",symbol:"TRB",name:"Tellor"},{id:"radicle",symbol:"RAD",name:"Radicle"},
  {id:"gitcoin",symbol:"GTC",name:"Gitcoin"},{id:"ens",symbol:"ENS",name:"Ethereum Name Service"},{id:"space-id",symbol:"ID",name:"Space ID"},
  {id:"cyberconnect",symbol:"CYBER",name:"CyberConnect"},{id:"hooked-protocol",symbol:"HOOK",name:"Hooked Protocol"},{id:"educational-coin",symbol:"EDU",name:"Open Campus"},
  {id:"worldcoin-wld",symbol:"WLD",name:"Worldcoin"},{id:"sei-network",symbol:"SEI",name:"Sei"},{id:"ordinals",symbol:"ORDI",name:"ORDI"},
  {id:"bonk",symbol:"BONK",name:"Bonk"},{id:"akash-network",symbol:"AKT",name:"Akash Network"},{id:"singularitynet",symbol:"AGIX",name:"SingularityNET"},
  {id:"wootrade",symbol:"WOO",name:"WOO"},{id:"ronin",symbol:"RON",name:"Ronin"},{id:"pyth-network",symbol:"PYTH",name:"Pyth Network"},
  {id:"jupiter-exchange-solana",symbol:"JUP",name:"Jupiter"},{id:"manta-network",symbol:"MANTA",name:"Manta Network"},{id:"dymension",symbol:"DYM",name:"Dymension"},
  {id:"altlayer",symbol:"ALT",name:"AltLayer"},{id:"beam-2",symbol:"BEAM",name:"Beam"},{id:"arkham",symbol:"ARKM",name:"Arkham"},
  {id:"starknet",symbol:"STRK",name:"Starknet"},{id:"ethena",symbol:"ENA",name:"Ethena"},{id:"dogwifhat",symbol:"WIF",name:"dogwifhat"},
  {id:"my-neighbor-alice",symbol:"ALICE",name:"My Neighbor Alice"},{id:"illuvium",symbol:"ILV",name:"Illuvium"},{id:"vulcan-forged",symbol:"PYR",name:"Vulcan Forged"},
  {id:"yield-guild-games",symbol:"YGG",name:"Yield Guild Games"},{id:"star-atlas",symbol:"ATLAS",name:"Star Atlas"},{id:"aurora-near",symbol:"AURORA",name:"Aurora"},
  {id:"metis-token",symbol:"METIS",name:"Metis"},{id:"boba-network",symbol:"BOBA",name:"Boba Network"},{id:"ribbon-finance",symbol:"RBN",name:"Ribbon Finance"},
  {id:"hashflow",symbol:"HFT",name:"Hashflow"},{id:"magic",symbol:"MAGIC",name:"Magic"},{id:"looksrare",symbol:"LOOKS",name:"LooksRare"},
  {id:"x2y2",symbol:"X2Y2",name:"X2Y2"},{id:"alchemy-pay",symbol:"ACH",name:"Alchemy Pay"},{id:"rss3",symbol:"RSS3",name:"RSS3"},
  {id:"stargate-finance",symbol:"STG",name:"Stargate Finance"},{id:"synapse-2",symbol:"SYN",name:"Synapse"},{id:"hop-protocol",symbol:"HOP",name:"Hop Protocol"},
  {id:"across-protocol",symbol:"ACX",name:"Across Protocol"},{id:"celer-network",symbol:"CELR",name:"Celer Network"},{id:"layerzero",symbol:"ZRO",name:"LayerZero"},
  {id:"eigenlayer",symbol:"EIGEN",name:"EigenLayer"},{id:"ether-fi",symbol:"ETHFI",name:"ether.fi"},{id:"renzo",symbol:"REZ",name:"Renzo"},
  {id:"puffer",symbol:"PUFFER",name:"Puffer"},{id:"kelp-dao",symbol:"KELP",name:"Kelp DAO"},{id:"swell-network",symbol:"SWELL",name:"Swell"},
  {id:"mantle",symbol:"MNT",name:"Mantle"},{id:"blast",symbol:"BLAST",name:"Blast"},{id:"linea",symbol:"LINEA",name:"Linea"},
  {id:"base",symbol:"BASE",name:"Base"},{id:"zksync",symbol:"ZK",name:"zkSync"},{id:"scroll",symbol:"SCROLL",name:"Scroll"},
  {id:"taiko",symbol:"TAIKO",name:"Taiko"},{id:"aztec",symbol:"AZTEC",name:"Aztec"},{id:"fuel",symbol:"FUEL",name:"Fuel"},
  {id:"aleo",symbol:"ALEO",name:"Aleo"},{id:"ironfish",symbol:"IRON",name:"Iron Fish"},{id:"namada",symbol:"NAM",name:"Namada"},
  {id:"penumbra",symbol:"PEN",name:"Penumbra"},{id:"berachain",symbol:"BERA",name:"Berachain"},{id:"monad",symbol:"MONAD",name:"Monad"}
];

export const STORAGE_KEYS = {
  portfolio: "minimal-crypto-portfolio-v2-portfolio",
  watchlist: "minimal-crypto-portfolio-v2-watchlist",
  alerts:    "minimal-crypto-portfolio-v2-alerts",
  wallets:   "minimal-crypto-portfolio-v2-wallets",
  fx:        "minimal-crypto-fx-rates",
  benchmarks:"minimal-crypto-benchmarks",
  currency:  "minimal-crypto-preferred-currency",
  cgApiKey:  "minimal-crypto-coingecko-api-key",
  theme:     "minimal-crypto-preferred-theme"
};

export const CG_API_KEY_TTL_MS = 1000 * 60 * 60 * 24 * 30; // 30 days
export const DEFAULT_CG_API_KEY = "CG-DATA-API"; // CoinGecko demo key for basic access

export const CURRENCY_CONFIG = {
  usd: { locale: "en-US", currency: "USD", symbol: "$", name: "USD" },
  eur: { locale: "de-DE", currency: "EUR", symbol: "€", name: "EUR" },
  gbp: { locale: "en-GB", currency: "GBP", symbol: "£", name: "GBP" },
  jpy: { locale: "ja-JP", currency: "JPY", symbol: "¥", name: "JPY" },
  aud: { locale: "en-AU", currency: "AUD", symbol: "A$", name: "AUD" },
  cad: { locale: "en-CA", currency: "CAD", symbol: "C$", name: "CAD" }
};

// Very rough benchmark assumptions
export const BENCHMARK_RETURNS = {
  month:   { sp: 0.02,  nasdaq: 0.025 },
  quarter: { sp: 0.05,  nasdaq: 0.065 },
  year:    { sp: 0.08,  nasdaq: 0.11 },
  hasLive: false
};

export const NEWS_API_URL = "https://api.coinstats.app/public/v1/news/latest?skip=0&limit=25";
